### ISSUE TITLE
Regarding ID functionality for match_most_similar() and group_similar_strings()

### ISSUE THREAD

**Issue by ParticularMiner** [Bergvca/string_grouper#22]
Hi Bergcva,

@justasojourner and I have been discussing your comments in Issue #19 on adding ID functionality for functions _match_most_similar()_ and _group_similar_strings()_.  While neither of us find the proposed additional functionality (as we imagine it) for these functions to be particularly useful for our own use, we thought you might have a better idea so we would first check with you on what exactly you meant by it. 

Do let us know your thoughts on this.

Cheers!

**Comment by justasojourner** [comment]
To explain/add — as I investigated and thought this through I realised that if there were three match check value rows, say ‘fooo’, ‘fooob’ & ‘bar’, if they were grouped and ‘fooo’ & ‘fooob’ were grouped in one value, ‘fooo’ then, in essence, ‘fooob’ would be cut off. **If the row ‘fooob’ was cut out then obviously the ID (being in the same row) would be cut out.** 

This would result in lost data, which is not desirable. The point (well for me in a business use case) of having the relevant row ID (what is the DB row ID) returned in the DataFrame is to be able to identify a **specific row** as being a duplicate. If the row is, in essence, deleted through grouping then the data is lost. 

HTH explain.

**Comment by Bergvca** [comment]
Hi both, 

The idea of the *group_similar_strings* function is that you do a deduplication in one go. In your example "fooob" can be seen as kind of a group-identifier. Basically a "random" string within the group of similar strings that gets picked to be the group-identifier. By adding an ID field, you can use this ID as a group-identifier, instead of the string. 

Now I don't really have a business use case for this either, but I could imagine something like:

You have a database with a lot of companies and you want to clean this by removing duplicates. The companies also have other attributes (e.g. phone number, address) and you want to pick one as the "correct" one. For this having an ID would be useful. 

This is a contrived example though. We could also wait to see if people actually have this use case.

**Comment by ParticularMiner** [comment]
Hmmm ...  make sense.  I'll code it.

**Comment by Bergvca** [comment]
Thanks! Merged and updated in pypi - the latest version is now 0.3.2
